spring:
  application:
    name: Order_Services
  datasource:
    url: jdbc:mysql://localhost:3306/order_services
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
