import { useEffect, useRef, useState } from 'react'
import { api, send, states, transitions, money, date, list } from './api.js'
import { gsap } from 'gsap'
import { useGSAP } from '@gsap/react'
import { SquaresFour, Package, Warehouse, ArrowUUpLeft, ShoppingBag, ShoppingCart, Truck, ArrowUpRight, ArrowsClockwise, List, MagnifyingGlass, Plus, DownloadSimple, Stack, CurrencyCircleDollar, WarningCircle } from '@phosphor-icons/react'
import Welcome from './Welcome.jsx'

gsap.registerPlugin(useGSAP)
const navIcons = { overview: SquaresFour, orders: Package, inventory: Warehouse, returns: ArrowUUpLeft, catalog: ShoppingBag, cart: ShoppingCart, mine: Package, delivery: Truck }

const menus = {
  ADMIN: [['overview', 'Overview'], ['orders', 'Orders'], ['inventory', 'Products & stock'], ['returns', 'Returns']],
  USER: [['catalog', 'Products'], ['cart', 'Cart'], ['mine', 'My orders']],
  SHIPPER: [['delivery', 'My deliveries']],
}
const titles = { overview: 'Operations overview', orders: 'Order management', inventory: 'Products & inventory', returns: 'Return requests', catalog: 'Explore products', cart: 'Your cart', mine: 'My orders', delivery: 'Delivery tasks' }
const subtitles = { overview: 'Monitor activity, control stock and process orders.', orders: 'Track progress and coordinate every order.', inventory: 'Manage your catalogue, prices and actual stock levels.', returns: 'Track requests, inspect products and export reports.', catalog: 'Choose products and add them to your cart.', cart: 'Review your products before placing an order.', mine: 'Your order details and delivery journey.', delivery: 'Accept assigned orders and update delivery outcomes.' }

function Badge({ value }) { return <span className="badge" data-state={value}>{states[value] || value || '—'}</span> }
function Empty({ text = 'No data yet', description = 'New activity will appear here.' }) { return <div className="py-20 text-center"><div className="mx-auto mb-5 flex size-14 items-center justify-center rounded-xl border border-[var(--line)] text-2xl muted">∅</div><h3 className="font-semibold">{text}</h3><p className="muted mt-2 text-sm">{description}</p></div> }
function Modal({ title, children, close }) {
  const ref = useRef(null)
  useEffect(() => { ref.current.showModal() }, [])
  return <dialog ref={ref} onCancel={close} aria-labelledby="modal-title"><header className="flex items-center justify-between border-b border-[var(--line)] p-6"><h2 id="modal-title" className="text-xl font-semibold">{title}</h2><button onClick={close} className="secondary" aria-label="Close">×</button></header><div className="p-6">{children}</div></dialog>
}
function Form({ fields, submit, label = 'Save changes', initial = {} }) {
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState('')
  async function handle(event) {
    event.preventDefault(); setBusy(true); setError('')
    const entries = new FormData(event.currentTarget)
    const data = Object.fromEntries(fields.flatMap(field => {
      const value = entries.get(field.name)
      return value === null || (value === '' && !field.keepEmpty) ? [] : [[field.name, field.type === 'number' ? Number(value) : value]]
    }))
    try { await submit(data) } catch (err) { setError(err.message) } finally { setBusy(false) }
  }
  return <form onSubmit={handle} className="grid gap-5">{fields.map(field => <label key={field.name}>{field.label}{field.options ? <select name={field.name} defaultValue={initial[field.name] ?? ''} required={field.required !== false}><option value="">Select {field.label.toLowerCase()}</option>{field.options.map(option => <option key={option.value} value={option.value}>{option.label}</option>)}</select> : <input name={field.name} type={field.type || 'text'} defaultValue={initial[field.name] ?? ''} required={field.required !== false} min={field.min} max={field.max} maxLength={field.maxLength || 255} step={field.step} autoComplete={field.autoComplete || 'off'} />}</label>)}{error && <p className="error rounded-lg p-3 text-sm" role="alert">{error}</p>}<button disabled={busy} className="primary mt-1">{busy ? 'Processing…' : label}</button></form>
}
function Login({ onLogin }) {
  return <Welcome>{import.meta.env.DEV && <div className="mb-6 rounded-xl border border-[#d5f56b]/30 bg-[#d5f56b]/10 p-4 text-sm text-[#e5f7be]"><p className="font-medium">Try it without a backend</p><p className="mt-2 break-all text-xs">demo@order.local · Demo123!</p><p className="mt-2 text-xs text-[#b6c1d2]">The demo account includes all three roles to explore the interface.</p></div>}<Form initial={import.meta.env.DEV ? { email: 'demo@order.local', password: 'Demo123!' } : {}} label="Sign in" fields={[{ name: 'email', label: 'Email', type: 'email', autoComplete: 'username' }, { name: 'password', label: 'Password', type: 'password', maxLength: 72, autoComplete: 'current-password' }]} submit={async data => onLogin(await send('/auth/login', 'POST', data))} /></Welcome>
}
function Pager({ page, setPage, data }) { return <div className="flex items-center justify-between border-t border-[var(--line)] px-5 py-4 text-xs muted"><span>{data?.totalElements ?? list(data).length} results · Page {page + 1}/{Math.max(data?.totalPages || 1, 1)}</span><div className="flex gap-2"><button className="secondary" disabled={page === 0} onClick={() => setPage(page - 1)}>Previous</button><button className="secondary" disabled={page + 1 >= (data?.totalPages || 1)} onClick={() => setPage(page + 1)}>Next</button></div></div> }
function Table({ columns, rows, keyField, onClick }) { return <div className="overflow-x-auto"><table className="w-full"><thead><tr>{columns.map(column => <th key={column.label}>{column.label}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={row[keyField] || index}>{columns.map((column, i) => <td key={column.label}>{i === 0 && onClick ? <button className="text-left font-semibold text-[var(--accent)] underline-offset-4 hover:underline" onClick={() => onClick(row)}>{column.render(row)}</button> : column.render(row)}</td>)}</tr>)}</tbody></table></div> }

export default function App() {
  const [user, setUser] = useState(null)
  const [checking, setChecking] = useState(true)
  const [role, setRole] = useState('')
  const [view, setView] = useState('overview')
  const [page, setPage] = useState(0)
  const [query, setQuery] = useState('')
  const [search, setSearch] = useState('')
  const [filter, setFilter] = useState('')
  const [data, setData] = useState(null)
  const [stats, setStats] = useState(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')
  const [revision, setRevision] = useState(0)
  const [modal, setModal] = useState(null)
  const [notice, setNotice] = useState('')
  const [mobile, setMobile] = useState(false)
  const [actionBusy, setActionBusy] = useState(false)
  const workspace = useRef(null)
  useGSAP(() => {
    if (!user || !workspace.current) return
    const media = gsap.matchMedia()
    media.add('(prefers-reduced-motion: no-preference)', () => {
      gsap.from('.workspace-heading, .metric-card, .workspace-banner, .data-panel', { y: 20, opacity: 0, duration: .6, stagger: .07, ease: 'power3.out', clearProps: 'all' })
    })
    return () => media.revert()
  }, { scope: workspace, dependencies: [user, view], revertOnUpdate: true })
  function loggedIn(account) { setError(''); setUser(account); const active = account.roles.find(item => menus[item]); setRole(active || ''); setView(menus[active]?.[0][0] || 'mine') }
  useEffect(() => { api('/auth/me').then(loggedIn).catch(err => { if (err.status !== 401 && !import.meta.env.DEV) setError(err.message) }).finally(() => setChecking(false)) }, [])
  useEffect(() => { if (!notice) return; const timer = setTimeout(() => setNotice(''), 5000); return () => clearTimeout(timer) }, [notice])
  function navigate(next) { setView(next); setPage(0); setFilter(''); setSearch(''); setQuery(''); setModal(null); setMobile(false) }
  useEffect(() => {
    if (!user) return
    let active = true
    setLoading(true); setError(''); setData(null)
    const params = new URLSearchParams({ page: String(page), size: '10' })
    if (search) params.set('query', search)
    if (filter) params.set(view === 'returns' ? 'filterBy' : 'state', filter)
    const paths = { overview: '/orders?size=5', orders: `/orders?${params}`, inventory: `/inventories/products-in-stock?${params}`, returns: `/orders/returns?${params}`, catalog: `/catalog?${params}`, cart: '/carts', mine: `/orders/mine?${params}`, delivery: `/shipper/orders?${params}` }
    const summary = view === 'overview' || view === 'inventory' ? api('/inventories') : view === 'returns' ? api('/orders/returns/summary!') : Promise.resolve(null)
    Promise.all([api(paths[view]), summary]).then(([result, totals]) => { if (active) { setData(result); setStats(totals) } }).catch(err => { if (active) { setError(err.message); if (err.status === 401) setUser(null) } }).finally(() => { if (active) setLoading(false) })
    return () => { active = false }
  }, [user, view, page, search, filter, revision])
  function done(text = 'Changes saved') { setModal(null); setNotice(text); setRevision(value => value + 1) }
  async function action(callback) { setActionBusy(true); try { await callback() } catch (err) { setNotice(err.message) } finally { setActionBusy(false) } }
  async function detail(row) {
    await action(async () => {
      const id = row.orderId || row.id || row.returnId
      const path = view === 'returns' ? `/orders/returns/${id}` : view === 'mine' ? `/orders/tracking/${id}` : role === 'SHIPPER' ? `/shipper/orders/${id}` : `/orders/${id}`
      const fresh = await api(path)
      setModal({ type: 'detail', data: { ...row, ...fresh, state: fresh.state || fresh.orderTrackingStatus || row.state, orderId: id } })
    })
  }
  async function exportReturns() {
    if (user.email === 'demo@order.local') {
      const csv = '\uFEFFRequest ID,Customer,Status\n' + list(data).map(item => [item.returnId, item.customerName, states[item.orderReturnStatus] || item.orderReturnStatus].map(value => `"${String(value || '').replaceAll('"', '""')}"`).join(',')).join('\n')
      const url = URL.createObjectURL(new Blob([csv], { type: 'text/csv;charset=utf-8' }))
      const link = document.createElement('a'); link.href = url; link.download = 'demo-returns.csv'; link.click(); URL.revokeObjectURL(url)
      setNotice('Demo data exported'); return
    }
    await action(async () => {
      const response = await fetch(`/api/orders/return/export?filterBy=${encodeURIComponent(filter || 'ALL_REQUESTS')}`, { credentials: 'include' })
      if (!response.ok) throw new Error('Unable to export the report.')
      const url = URL.createObjectURL(await response.blob()); const link = document.createElement('a'); link.href = url; link.download = 'order-returns.csv'; link.click(); URL.revokeObjectURL(url); setNotice('CSV report exported')
    })
  }
  if (checking) return <div className="p-12 muted" role="status">Checking your session…</div>
  if (!user) return <><Login onLogin={loggedIn} />{error && <p className="error fixed bottom-4 right-4 rounded-lg p-4" role="alert">{error}</p>}</>
  const rows = view === 'catalog' && search ? list(data).filter(item => `${item.productName} ${item.description || ''}`.toLocaleLowerCase('en-GB').includes(search.toLocaleLowerCase('en-GB'))) : list(data)
  const orderColumns = [{ label: 'Order ID', render: row => row.orderId || row.id }, { label: 'Customer', render: row => row.customerName || row.recipientName || '—' }, { label: 'Created', render: row => date(row.createdAt) }, { label: 'Total', render: row => money(row.total ?? row.totalAmount) }, { label: 'Status', render: row => <Badge value={row.state} /> }]
  const inventoryColumns = [{ label: 'Product', render: row => row.productName }, { label: 'Variant ID', render: row => <span className="font-mono text-xs">{row.productVariantId}</span> }, { label: 'Price', render: row => money(row.productPrice) }, { label: 'Stock', render: row => row.productStockQuantity }, { label: 'Status', render: row => <Badge value={row.productStockState} /> }, { label: 'Actions', render: row => <div className="flex gap-2"><button className="secondary" onClick={() => setModal({ type: 'stock', data: row })}>Stock</button>{row.productId && <button className="secondary" onClick={() => setModal({ type: 'editProduct', data: row })}>Edit</button>}</div> }]
  const returnColumns = [{ label: 'Request ID', render: row => row.returnId }, { label: 'Customer', render: row => row.customerName }, { label: 'Requested', render: row => date(row.initialTime) }, { label: 'Reason', render: row => row.reasonReturn }, { label: 'Status', render: row => <Badge value={row.orderReturnStatus} /> }]
  return <div ref={workspace} className="workspace min-h-dvh w-full max-w-full overflow-x-clip lg:grid lg:grid-cols-[252px_1fr]">
    <a href="#content" className="sr-only focus:not-sr-only focus:fixed focus:z-50 focus:bg-[var(--surface)] focus:p-4">Skip to content</a>
    <aside className={`sidebar ${mobile ? 'block' : 'hidden'} p-5 lg:sticky lg:top-0 lg:flex lg:h-dvh lg:flex-col`}><a href="#content" className="mb-14 mt-3 flex items-center gap-3 text-xl font-semibold tracking-tight"><span className="brand-mark"><Stack size={22} weight="bold" /></span>order<span className="text-[#95a4b8] font-normal">/</span></a><nav aria-label="Workspace navigation" className="grid gap-2">{(menus[role] || []).map(([key, label]) => { const Icon = navIcons[key]; return <button key={key} onClick={() => navigate(key)} aria-current={view === key ? 'page' : undefined} className={`nav-item ${view === key ? 'active' : ''}`}><Icon size={20} weight={view === key ? 'fill' : 'regular'} />{label}{view === key && <span className="ml-auto size-1.5 rounded-full bg-current" />}</button> })}</nav><div className="mt-auto pt-12"><div className="sidebar-note overflow-hidden rounded-2xl p-5"><div className="mb-5 flex items-center justify-between"><Stack size={25} /><ArrowUpRight size={20} /></div><p className="text-lg font-medium leading-snug">Fewer steps.<br />More clarity.</p><p className="mt-3 text-xs leading-relaxed text-[#adb8c8]">Products, orders and deliveries in one workspace.</p></div><div className="mt-6 flex items-center justify-between text-[11px] text-[#adb8c8]"><span>Order Workspace</span><span>v1.0</span></div></div></aside>
    <div className="min-w-0"><header className="workspace-topbar flex min-h-20 flex-wrap items-center justify-between gap-3 px-5 py-4 lg:px-10"><div className="flex items-center gap-3"><button className="secondary lg:hidden" aria-label="Open navigation" onClick={() => setMobile(!mobile)}><List size={20} />Menu</button><span className="muted text-xs">Workspace <span className="mx-2">/</span> <span className="text-[var(--ink)]">{titles[view]}</span></span></div><div className="flex items-center gap-3">{user.roles.length > 1 && <select aria-label="Active role" className="max-w-32 text-xs" value={role} onChange={e => { setRole(e.target.value); navigate(menus[e.target.value][0][0]) }}>{user.roles.filter(item => menus[item]).map(item => <option key={item}>{item}</option>)}</select>}<div className="hidden text-right sm:block"><p className="text-xs font-semibold">{user.userName}</p><p className="muted mt-1 text-[10px]">{role}</p></div><div className="flex size-9 items-center justify-center rounded-lg bg-[var(--soft)] text-sm font-semibold text-[var(--accent)]">{(user.userName || user.email || 'U')[0].toUpperCase()}</div><button className="text-xs muted hover:underline" disabled={actionBusy} onClick={() => action(async () => { await send('/auth/logout', 'POST', {}); setUser(null) })}>Sign out</button></div></header>
    <main id="content" className="mx-auto w-full max-w-[1500px] overflow-x-hidden px-5 py-8 lg:px-10 lg:py-10">{user.email === 'demo@order.local' && <div className="demo-banner mb-7 flex flex-wrap items-center gap-3 rounded-xl px-4 py-3 text-xs"><WarningCircle size={18} /><span>Demo mode · Sample data is for exploring the interface only and is not sent to the backend.</span></div>}<div className="workspace-heading mb-9 flex flex-wrap items-start justify-between gap-4"><div><p className="muted mb-2 text-xs">{new Date().toLocaleDateString('en-GB', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' })}</p><h1 className="max-w-6xl text-[clamp(1.8rem,3vw,2.75rem)] font-medium tracking-[-.045em]">{titles[view]}</h1><p className="muted mt-3 text-sm">{subtitles[view]}</p></div><div className="flex gap-2">{view === 'inventory' && <><button className="secondary" onClick={() => setModal({ type: 'variant' })}>Add variant</button><button className="primary" onClick={() => setModal({ type: 'product' })}><Plus size={16} />Product</button></>}{view === 'returns' && <button className="secondary" disabled={actionBusy} onClick={exportReturns}><DownloadSimple size={16} />Export CSV</button>}<button className="secondary" disabled={loading} onClick={() => setRevision(value => value + 1)}><ArrowsClockwise size={16} />Refresh</button></div></div>
    {stats && <section className="mb-8 grid grid-flow-dense gap-4 sm:grid-cols-2 xl:grid-cols-4">{(view === 'returns' ? [['Open requests', stats.activeReturnCount], ['Awaiting inspection', stats.awaitInspectionCount], ['Processing time', stats.averageCycleTime ?? '—'], ['Total refunds', money(stats.totalRefunds)]] : [['Inventory value', money(stats.totalInventoryValue)], ['Products in stock', stats.totalProductsInStock], ['Low stock', stats.totalProductsPrepareToOutOfStock], ['Orders listed', data?.totalElements ?? '—']]).map(([label, value], index) => { const Icon = [CurrencyCircleDollar, Package, WarningCircle, Stack][index]; return <div className={`metric-card panel p-6 ${index === 0 ? 'metric-featured' : ''}`} key={label}><div className="flex items-center justify-between"><p className="muted text-xs">{label}</p><span className="metric-icon"><Icon size={20} /></span></div><p className="mt-5 text-[clamp(1.5rem,2vw,2rem)] font-medium tracking-[-.04em] tabular-nums">{value ?? '—'}</p><p className="muted mt-5 flex items-center gap-2 text-[10px]"><span className="size-1 rounded-full bg-current" />{view === 'returns' ? 'Tracking return requests' : 'Based on system data'}</p></div> })}</section>}
    {view === 'overview' && <div className="workspace-banner group relative mb-8 flex min-h-52 flex-wrap items-center justify-between gap-6 overflow-hidden rounded-2xl px-7 py-8 md:px-10"><div className="banner-orbit" aria-hidden="true"><span /><span /><span /></div><div className="relative z-10 max-w-xl"><p className="mb-4 text-xs text-[#b8c4d4]">One workflow. Every touchpoint.</p><h2 className="max-w-xl text-2xl font-medium tracking-tight md:text-3xl">Orders go further.<br />Stay in the know.</h2><p className="mt-4 max-w-md text-xs leading-relaxed text-[#b8c4d4]">Track every status, assign deliveries and keep every detail within reach.</p></div><button className="relative z-10 inline-flex items-center gap-5 rounded-xl bg-[#d7f594] px-5 py-4 text-sm font-semibold text-[#19231a] transition-transform hover:-translate-y-1" onClick={() => navigate('orders')}>View orders<ArrowUpRight size={20} /></button></div>}
    <section className="data-panel panel overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-4 border-b border-[var(--line)] px-5 py-5"><h2 className="font-semibold">{view === 'overview' ? 'Recent orders' : titles[view]}{data && <span className="muted ml-3 text-xs font-normal">{data.totalElements ?? rows.length} results</span>}</h2>{view !== 'cart' && <form className="flex flex-wrap gap-2" onSubmit={e => { e.preventDefault(); setPage(0); setSearch(query) }}><input className="sm:max-w-52 text-xs" aria-label="Search" placeholder="Search…" value={query} onChange={e => setQuery(e.target.value)} /><button className="secondary inline-flex items-center gap-2"><MagnifyingGlass size={16} />Search</button>{['orders', 'returns', 'mine', 'delivery'].includes(view) && <select className="sm:max-w-44 text-xs" aria-label="Filter by status" value={filter} onChange={e => { setFilter(e.target.value); setPage(0) }}><option value="">All statuses</option>{(view === 'returns' ? ['PENDING', 'IN_TRANSIT', 'WAREHOUSE_RECEIVED', 'INSPECTING', 'RESTOCKED', 'REFUNDED', 'REJECTED'] : Object.keys(transitions).concat(['DELIVERED', 'CANCELLED'])).map(state => <option key={state} value={state}>{states[state]}</option>)}</select>}</form>}</div>
    {loading ? <div className="grid gap-5 p-6" role="status" aria-label="Loading data">{[1, 2, 3, 4].map(key => <div className="skeleton h-12" key={key} />)}</div> : error ? <div className="p-8"><p className="error rounded-lg p-4 text-sm" role="alert">{error}</p><button className="secondary mt-4" onClick={() => setRevision(value => value + 1)}>Try again</button></div> : view === 'cart' ? <Cart data={data} done={done} setModal={setModal} action={action} busy={actionBusy} /> : !rows.length ? <Empty /> : view === 'catalog' ? <div className="grid gap-4 p-5 sm:grid-cols-2 xl:grid-cols-3">{rows.map(row => <article className="group flex flex-col rounded-xl border border-[var(--line)] p-5" key={row.productVariantId}><div className="mb-5 flex h-24 items-center justify-center rounded-lg bg-[var(--soft)] text-xl font-semibold text-[var(--accent)]">{row.productName?.slice(0, 2).toUpperCase()}</div><h3 className="font-semibold">{row.productName}</h3><p className="muted mt-2 text-xs">{row.description || row.productVariant}</p><p className="mt-5 text-lg font-semibold">{money(row.price)}</p><p className="muted mb-4 mt-2 text-xs">{row.quantityInStock} items in stock</p><button disabled={actionBusy || !row.quantityInStock} className="primary mt-auto w-full" onClick={() => action(async () => { await send('/carts/items', 'POST', { productVariantId: row.productVariantId, quantity: 1 }); setNotice('Added to cart') })}>Add to cart</button></article>)}</div> : <Table columns={view === 'inventory' ? inventoryColumns : view === 'returns' ? returnColumns : orderColumns} rows={rows} keyField={view === 'returns' ? 'returnId' : view === 'inventory' ? 'productVariantId' : 'orderId'} onClick={view === 'inventory' ? null : detail} />}
    {!loading && !error && view !== 'cart' && <Pager page={page} setPage={setPage} data={data} />}</section><footer className="muted mt-6 flex justify-between text-[10px]"><span>Order Workspace</span><span>{user.email === 'demo@order.local' ? 'Sample data · For exploring the interface only' : 'Connected to the order management system'}</span></footer></main></div>
    {notice && <div role="status" className="panel fixed bottom-6 right-6 z-50 max-w-sm p-4 text-sm shadow-lg">{notice}<button className="ml-4 muted" aria-label="Dismiss notification" onClick={() => setNotice('')}>×</button></div>}
    {modal && <Modal title={{ stock: 'Update stock', editProduct: 'Edit product', product: 'Create product', variant: 'Add variant', detail: 'Details', checkout: 'Confirm order' }[modal.type]} close={() => setModal(null)}>
      {modal.type === 'stock' && <><p className="muted mb-5 text-sm">{modal.data.productName} · Enter the actual total stock, not the quantity to add.</p><Form initial={{ quantity: modal.data.productStockQuantity }} fields={[{ name: 'quantity', label: 'Stock quantity', type: 'number', min: 0, step: 1 }]} submit={async body => { await send(`/inventories/${encodeURIComponent(modal.data.productVariantId)}/quantity`, 'PUT', body); done() }} /></>}
      {modal.type === 'editProduct' && <Form initial={{ productName: modal.data.productName, productType: modal.data.productType, productPrice: modal.data.productPrice, quantityInStock: modal.data.productStockQuantity, productDescription: modal.data.productDescription }} fields={[{ name: 'productName', label: 'Product name' }, { name: 'productType', label: 'Product type', maxLength: 100 }, { name: 'productPrice', label: 'Price (VND)', type: 'number', min: 0, step: '.01' }, { name: 'quantityInStock', label: 'Total stock', type: 'number', min: 0, step: 1 }, { name: 'productDescription', label: 'Variant description', required: false, keepEmpty: true }]} submit={async body => { await send(`/inventories/productsInStock/${encodeURIComponent(modal.data.productId)}/variants/${encodeURIComponent(modal.data.productVariantId)}`, 'PATCH', body); done() }} />}
      {modal.type === 'product' && <Form fields={[{ name: 'productId', label: 'Product ID' }, { name: 'productName', label: 'Product name' }, { name: 'productType', label: 'Product type', maxLength: 100 }]} submit={async body => { await send('/products', 'POST', body); done('Product created. Add a variant to set its price and stock.') }} />}
      {modal.type === 'variant' && <Form fields={[{ name: 'productId', label: 'Product ID' }, { name: 'productVariant', label: 'Variant description' }, { name: 'price', label: 'Price (VND)', type: 'number', min: 0, step: '.01' }]} submit={async body => { await send(`/products/${encodeURIComponent(body.productId)}/variants`, 'POST', body); done() }} />}
      {modal.type === 'detail' && <Detail data={modal.data} role={role} view={view} done={done} />}
      {modal.type === 'checkout' && <Checkout done={done} />}
    </Modal>}
  </div>
}

function Cart({ data, done, setModal, action, busy }) {
  if (!data?.items?.length) return <Empty text="Your cart is empty" description="Visit Products to add the items you want to buy." />
  return <div className="p-5">{data.items.map(item => <div key={item.cartItemId} className="flex flex-wrap items-center justify-between gap-4 border-b border-[var(--line)] py-5"><div><h3 className="text-sm font-semibold">{item.productName}</h3><p className="mt-2"><Badge value={item.stockStatus} /></p></div><div className="flex items-center gap-4"><button className="secondary" aria-label={`Decrease quantity of ${item.productName}`} disabled={busy} onClick={() => action(async () => { await send(`/carts/items/${item.cartItemId}/quantity`, 'PATCH', { quantityChange: -1 }); done('Cart updated') })}>−</button><span className="text-sm">{item.quantity}</span><button className="secondary" aria-label={`Increase quantity of ${item.productName}`} disabled={busy} onClick={() => action(async () => { await send(`/carts/items/${item.cartItemId}/quantity`, 'PATCH', { quantityChange: 1 }); done('Cart updated') })}>+</button><span className="min-w-28 text-right text-sm font-semibold">{money(item.lineTotal)}</span></div></div>)}<div className="mt-6 flex flex-wrap items-center justify-between gap-4"><p className="text-lg font-semibold">Subtotal: {money(data.subtotal)}</p><button className="primary" onClick={() => setModal({ type: 'checkout' })}>Proceed to checkout</button></div></div>
}
function Checkout({ done }) {
  const [choices, setChoices] = useState(null)
  const [summary, setSummary] = useState(null)
  const [discount, setDiscount] = useState('')
  const [error, setError] = useState('')
  useEffect(() => { Promise.all([api('/addresses'), api('/payments'), api('/discounts')]).then(([addresses, payments, discounts]) => setChoices({ addresses: list(addresses), payments: list(payments), discounts: list(discounts) })).catch(err => setError(err.message)) }, [])
  useEffect(() => { let active = true; setSummary(null); send('/orders/orders/summary', 'POST', discount ? { discountId: discount } : {}).then(value => { if (active) setSummary(value) }).catch(err => { if (active) setError(err.message) }); return () => { active = false } }, [discount])
  if (error) return <p className="error p-4 rounded-lg" role="alert">{error}</p>
  if (!choices) return <p role="status" className="muted">Loading checkout details…</p>
  if (!choices.addresses.length || !choices.payments.length) return <Empty text="Missing checkout details" description="Your account needs a delivery address and payment method in the system." />
  return <div><label className="mb-5">Discount code<select value={discount} onChange={e => setDiscount(e.target.value)}><option value="">None</option>{choices.discounts.map(item => <option key={item.discountId} value={item.discountId}>{item.discountType} · {item.discountValue}</option>)}</select></label>{summary && <div className="mb-6 grid gap-2 rounded-lg bg-[var(--canvas)] p-4 text-sm">{[['Subtotal', summary.subtotal], ['Discount', summary.discountAmount], ['Delivery fee', summary.shippingFee], ['Total payment', summary.total]].map(([label, value]) => <div className="flex justify-between" key={label}><span>{label}</span><strong>{money(value)}</strong></div>)}</div>}{summary && <Form label="Place order" fields={[{ name: 'addressId', label: 'Delivery address', options: choices.addresses.map(item => ({ value: item.addressId || item.id, label: item.address || item.shippingAddress || item.city || item.addressId })) }, { name: 'paymentId', label: 'Payment method', options: choices.payments.map(item => ({ value: item.paymentId || item.id, label: item.paymentMethod || item.paymentMethodInfo || item.method || item.paymentId })) }]} submit={async body => { const order = await send('/orders', 'POST', { ...body, ...(discount ? { discountId: discount } : {}) }); done(`Order placed successfully · ${order.id}`) }} />}</div>
}
function Detail({ data, role, view, done }) {
  const [shippers, setShippers] = useState([])
  const [failure, setFailure] = useState(false)
  const [error, setError] = useState('')
  const [busy, setBusy] = useState(false)
  useEffect(() => { if (role === 'ADMIN' && view !== 'returns') api('/shippers').then(value => setShippers(list(value))).catch(err => setError(err.message)) }, [role, view])
  async function update(path, method, body) { setBusy(true); setError(''); try { await send(path, method, body); done() } catch (err) { setError(err.message) } finally { setBusy(false) } }
  const items = data.items || data.purchasedItems || []
  return <div className="grid gap-5"><div className="flex items-center justify-between"><span className="font-mono text-xs break-all">{data.returnId || data.orderId}</span><Badge value={data.state || data.orderTrackingStatus || data.orderReturnStatus} /></div><dl className="grid gap-4 text-sm sm:grid-cols-2">{[['Customer', data.customerName || data.recipientName], ['Address', [data.shippingAddress, data.shippingCity].filter(Boolean).join(', ') || null], ['Payment', data.paymentMethodInfo], ['Estimated delivery', data.estimatedDelivery ? date(data.estimatedDelivery) : null], ['Days remaining', data.daysRemaining], ['Total', money(data.total ?? data.totalAmount)], ['Created', date(data.createdAt || data.initialTime)], ['Return reason', data.reasonReturn]].filter(([, value]) => value != null).map(([label, value]) => <div key={label}><dt className="muted text-xs">{label}</dt><dd className="mt-1 break-words">{value}</dd></div>)}</dl>{items.length > 0 && <div className="border-y border-[var(--line)] py-3">{items.map((item, index) => <div key={item.orderItemId || index} className="flex justify-between gap-3 py-2 text-sm"><span>{item.productName || item.purchasedItemName} × {item.quantity ?? item.purchasedItemQuantity}</span><span>{money(item.unitPrice ?? item.purchasedItemPrice)}</span></div>)}</div>}{error && <p className="error rounded-lg p-3 text-sm" role="alert">{error}</p>}
    {role === 'ADMIN' && view !== 'returns' && <>{transitions[data.state]?.length > 0 && <Form label="Update status" fields={[{ name: 'state', label: 'New status', options: (transitions[data.state] || []).map(value => ({ value, label: states[value] })) }, { name: 'failureReason', label: 'Failure reason (for failed deliveries)', required: false, options: ['CUSTOMER_UNREACHABLE', 'CUSTOMER_ABSENT', 'CUSTOMER_REFUSED', 'INVALID_ADDRESS', 'OTHER'].map(value => ({ value, label: value })) }, { name: 'note', label: 'Note', required: false }]} submit={async body => { await send(`/orders/tracking/${data.orderId}/state`, 'PATCH', { ...body, ...(data.deliveryAttemptId ? { deliveryAttemptId: data.deliveryAttemptId } : {}) }); done() }} />}{['PROCESSING', 'DELIVERY_FAILED'].includes(data.state) && <Form label="Assign delivery" fields={[{ name: 'shipperId', label: 'Delivery driver', options: shippers.map(item => ({ value: item.shipperId || item.userId || item.id, label: item.userName || item.name || item.email })) }]} submit={async body => { await send(`/orders/${data.orderId}/shipper`, 'PATCH', body); done() }} />}</>}
    {role === 'SHIPPER' && <><p className="muted text-xs">Confirm that the recipient name and address match the order.</p>{data.state === 'PROCESSING' && <button className="primary" disabled={busy} onClick={() => update('/shipper/orders/receive', 'POST', { orderId: data.orderId })}>Accept delivery</button>}{data.state === 'SHIPPING' && <><button className="secondary" onClick={() => setFailure(!failure)}>{failure ? 'Switch to successful delivery' : 'Report failed delivery'}</button><Form label={failure ? 'Confirm failure' : 'Confirm delivery'} initial={{ customerName: data.customerName || data.recipientName, address: data.shippingAddress }} fields={[{ name: 'customerName', label: 'Customer name' }, { name: 'address', label: 'Delivery address' }, ...(failure ? [{ name: 'failureReason', label: 'Failure reason', options: [{ value: 'CUSTOMER_UNREACHABLE', label: 'Customer unreachable' }, { value: 'CUSTOMER_ABSENT', label: 'Customer absent' }, { value: 'CUSTOMER_REFUSED', label: 'Customer refused' }, { value: 'INVALID_ADDRESS', label: 'Invalid address' }, { value: 'OTHER', label: 'Other' }] }, { name: 'note', label: 'Note', required: false }] : [])]} submit={async body => { await send(`/shipper/orders/${failure ? 'failed' : 'delivered'}`, 'POST', { ...body, orderId: data.orderId, deliveryAttemptId: data.deliveryAttemptId }); done() }} /></>}</>}
  </div>
}
